(()=>{'use strict';
const root=document.documentElement,canvas=document.getElementById('book-world'),reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;

// Theme and mobile navigation.
const themeButton=document.getElementById('theme-toggle');try{const saved=localStorage.getItem('jeet-theme');if(saved==='light'||saved==='dark')root.dataset.theme=saved}catch{}function syncTheme(){const light=root.dataset.theme==='light';themeButton.textContent=light?'Dark mode ◐':'Light mode ◐';themeButton.setAttribute('aria-label',`Switch to ${light?'dark':'light'} theme`);document.querySelector('meta[name="theme-color"]').content=light?'#efeee7':'#10110f'}syncTheme();themeButton.addEventListener('click',()=>{root.dataset.theme=root.dataset.theme==='light'?'dark':'light';try{localStorage.setItem('jeet-theme',root.dataset.theme)}catch{}syncTheme()});
const menu=document.querySelector('.menu-button'),nav=document.getElementById('nav');menu.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',String(open));menu.textContent=open?'CLOSE':'MENU'});nav.querySelectorAll('a').forEach(link=>link.addEventListener('click',()=>{nav.classList.remove('open');menu.setAttribute('aria-expanded','false');menu.textContent='MENU'}));

// One dependency-free WebGL world: page stacks share one long spine; scroll moves a single camera through them.
const gl=canvas.getContext('webgl',{alpha:true,antialias:true,powerPreference:'low-power'});let glActive=false,program=null,buffer=null,aPosition=-1,aNormal=-1,aColor=-1,uViewport=null,uCamera=null,uTime=null;
const vertexShader=`attribute vec3 aPosition;attribute vec3 aNormal;attribute vec3 aColor;uniform vec2 uViewport;uniform vec4 uCamera;varying vec3 vColor;varying vec3 vNormal;varying float vDepth;void main(){float yaw=uCamera.z;float pitch=uCamera.w;vec3 q=aPosition-vec3(uCamera.x,uCamera.y,uViewport.y);float cx=cos(yaw),sx=sin(yaw);q=vec3(cx*q.x+sx*q.z,q.y,-sx*q.x+cx*q.z);float cp=cos(pitch),sp=sin(pitch);q=vec3(q.x,cp*q.y-sp*q.z,sp*q.y+cp*q.z);float d=max(.16,-q.z);float focal=1.0/tan(radians(43.0)*.5);gl_Position=vec4(q.x*focal/uViewport.x,q.y*focal,(1.0+0.08/d)*d-1.08,d);vColor=aColor;vNormal=normalize(aNormal);vDepth=d;}`;
const fragmentShader=`precision mediump float;varying vec3 vColor;varying vec3 vNormal;varying float vDepth;void main(){vec3 n=normalize(vNormal);float diffuse=max(dot(n,normalize(vec3(-.35,.78,.9))),0.0);float rim=pow(1.0-max(dot(n,vec3(0.0,0.0,1.0)),0.0),2.0);float light=.54+.42*diffuse+.08*rim;vec3 color=vColor*light;if(!gl_FrontFacing)color*=.82;float haze=smoothstep(11.0,37.0,vDepth);color=mix(color,vec3(.08,.09,.08),haze*.27);gl_FragColor=vec4(color,.91);}`;
function shader(type,source){const sh=gl.createShader(type);gl.shaderSource(sh,source);gl.compileShader(sh);if(!gl.getShaderParameter(sh,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(sh));return sh}
try{if(gl){program=gl.createProgram();gl.attachShader(program,shader(gl.VERTEX_SHADER,vertexShader));gl.attachShader(program,shader(gl.FRAGMENT_SHADER,fragmentShader));gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(program));gl.useProgram(program);buffer=gl.createBuffer();aPosition=gl.getAttribLocation(program,'aPosition');aNormal=gl.getAttribLocation(program,'aNormal');aColor=gl.getAttribLocation(program,'aColor');uViewport=gl.getUniformLocation(program,'uViewport');uCamera=gl.getUniformLocation(program,'uCamera');gl.enable(gl.DEPTH_TEST);gl.depthFunc(gl.LEQUAL);gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);gl.clearColor(0,0,0,0);glActive=true}}catch(error){console.warn('3D book fallback:',error);canvas.hidden=true}
const sceneEls=[...document.querySelectorAll('[data-scene]')],markerNum=document.getElementById('chapter-number'),markerName=document.getElementById('chapter-name');let progress=0,scrollMax=1,scrollY=0,pointerX=0,pointerY=0,targetX=0,targetY=0,lastChapter=-1,scrollStops=[];
function clamp(v,a,b){return Math.max(a,Math.min(b,v))}function smooth(a,b,x){x=clamp((x-a)/(b-a),0,1);return x*x*(3-2*x)}function readScroll(){scrollY=window.scrollY||document.documentElement.scrollTop;scrollMax=Math.max(1,document.documentElement.scrollHeight-innerHeight);const stops=sceneEls.map(el=>clamp((el.offsetTop+Math.min(el.offsetHeight*.48,innerHeight*.68)-innerHeight*.5)/scrollMax,0,1));scrollStops=stops;const raw=clamp(scrollY/scrollMax,0,1);let i=0;while(i<stops.length-2&&raw>stops[i+1])i++;const a=stops[i]??0,b=stops[i+1]??1,f=b===a?0:clamp((raw-a)/(b-a),0,1);progress=(i+f)/Math.max(1,stops.length-1);const chapter=Math.min(stops.length-1,Math.round(progress*(stops.length-1)));if(chapter!==lastChapter){lastChapter=chapter;markerNum.textContent=String(chapter+1).padStart(2,'0');markerName.textContent=sceneEls[chapter].dataset.chapter}}readScroll();window.addEventListener('scroll',readScroll,{passive:true});window.addEventListener('resize',readScroll,{passive:true});window.addEventListener('pointermove',e=>{targetX=(e.clientX/innerWidth-.5)*.32;targetY=(e.clientY/innerHeight-.5)*.18},{passive:true});


const cols=14,rows=18,vertsPerPage=cols*rows*6,stride=9,pageCount=sceneEls.length*10;const vertices=new Float32Array((pageCount*vertsPerPage+5000)*stride);let cursor=0;function pageHalfWidth(){const aspect=innerWidth/Math.max(1,innerHeight);return Math.min(2.18,Math.max(1.05,2.18*Math.min(1,aspect/1.6)))}function bookSpacing(){return innerWidth<700?9:7.05}
function addVertex(x,y,z,nx,ny,nz,r,g,b){vertices[cursor++]=x;vertices[cursor++]=y;vertices[cursor++]=z;vertices[cursor++]=nx;vertices[cursor++]=ny;vertices[cursor++]=nz;vertices[cursor++]=r;vertices[cursor++]=g;vertices[cursor++]=b}
function quad(a,b,c,d,color,normal=[0,0,1]){const [r,g,bv]=color;addVertex(...a,...normal,r,g,bv);addVertex(...b,...normal,r,g,bv);addVertex(...c,...normal,r,g,bv);addVertex(...a,...normal,r,g,bv);addVertex(...c,...normal,r,g,bv);addVertex(...d,...normal,r,g,bv)}
function page(z,side,layer,turn,t,flutter,color){const width=pageHalfWidth();for(let j=0;j<rows;j++)for(let i=0;i<cols;i++){const points=[];for(const [ii,jj] of [[i,j],[i+1,j],[i+1,j+1],[i,j+1]]){const u=ii/cols,v=jj/rows,rawX=side*u*width,rawY=-1.51+v*3.02;let x=rawX,y=rawY,zz=z-layer*.027;const curl=(.04*Math.sin(u*Math.PI)+flutter*Math.sin(t*1.5+layer*.6+v*2)*u*u)*Math.sin(v*Math.PI);zz+=curl;if(side>0&&turn!==0){const angle=turn*u,xx=x*Math.cos(angle),zr=-x*Math.sin(angle);x=xx;zz+=zr}if(side<0){x=rawX;zz+=.025*Math.sin(u*Math.PI)}points.push([x,y,zz])}const base=[...color],shade=.94+(.12*(j/rows))-(layer*.018);const col=base.map(v=>v*shade);let nx=side>0?Math.sin(turn*.5):0, nz=side>0?Math.cos(turn*.5):1;const n=[nx,.10,nz];quad(points[0],points[1],points[2],points[3],col,n)}}
function boxFace(points,color,normal){quad(points[0],points[1],points[2],points[3],color,normal)}
function buildWorld(t){cursor=0;const p=progress,spacing=bookSpacing(),cameraStart=innerWidth<700?8.8:4.15,cameraZ=cameraStart-p*spacing*(sceneEls.length-1);for(let s=0;s<sceneEls.length;s++){const z=-s*spacing,chapterP=s/(sceneEls.length-1);const turnStart=chapterP+.025,turnEnd=Math.min(1,chapterP+.19);let turn=s===sceneEls.length-1?-1.35*smooth(.88,1,p):-Math.PI*smooth(turnStart,turnEnd,p);if(s===0)turn=-1.24*(1-smooth(0,.105,p));const flutter=reduced?0:Math.sin(t*1.15+s*.85)*.018;const accent=s===2?[.88,.77,.60]:s===3?[.91,.89,.80]:[.91,.89,.82];for(let layer=4;layer>=0;layer--){const tint=layer===0?[accent[0],accent[1],accent[2]]:[.78+layer*.018,.76+layer*.018,.68+layer*.022];page(z,-1,layer,0,t,flutter,tint);page(z,1,layer,turn,t,flutter,tint)}
  // A continuous cloth-wrapped spine and board edges visually bind every chapter into one volume.
  const half=.095,top=1.53,bottom=-1.53,z0=z+.12,z1=z-spacing+.25,leather=[.15,.20,.16];boxFace([[-half,bottom,z0],[half,bottom,z0],[half,top,z0],[-half,top,z0]],leather,[0,0,1]);boxFace([[-half,top,z0],[-half,top,z1],[half,top,z1],[half,top,z0]],[.21,.25,.18],[0,1,0]);boxFace([[-half,bottom,z0],[half,bottom,z0],[half,bottom,z1],[-half,bottom,z1]],[.12,.16,.13],[0,-1,0]);boxFace([[-half,bottom,z1],[-half,top,z1],[half,top,z1],[half,bottom,z1]],[.19,.23,.17],[0,0,-1]);
  // The opening board is tangible and turns away at the start of the reading journey.
  if(s===0){page(z+.10,1,0,turn-.17,t,flutter,[.23,.29,.22]);}}
  // Fine paper rules, repeated sparingly as physical ink on a few visible leaves.
  for(let s=0;s<sceneEls.length;s++){const z=-s*spacing-.4;for(let line=0;line<4;line++){const y=-.47+line*.32;const c=[.48,.45,.36];quad([-.98,y,z],[ -.18,y,z],[ -.18,y+.007,z],[ -.98,y+.007,z],c,[0,0,1]);quad([.18,y,z],[.99,y,z],[.99,y+.007,z],[.18,y+.007,z],c,[0,0,1])}}
  gl.viewport(0,0,canvas.width,canvas.height);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.useProgram(program);gl.uniform2f(uViewport,canvas.width/canvas.height,cameraZ);const idleYaw=reduced?0:Math.sin(t*.17)*.025;gl.uniform4f(uCamera,pointerX*.55+idleYaw,pointerY*.22,cameraYaw(),cameraPitch());gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.bufferData(gl.ARRAY_BUFFER,vertices.subarray(0,cursor),gl.DYNAMIC_DRAW);const bytes=stride*4;for(const [loc,size,offset] of [[aPosition,3,0],[aNormal,3,3],[aColor,3,6]]){gl.enableVertexAttribArray(loc);gl.vertexAttribPointer(loc,size,gl.FLOAT,false,bytes,offset*4)}gl.drawArrays(gl.TRIANGLES,0,cursor/stride)}
function cameraYaw(){return (reduced?0:Math.sin(progress*Math.PI*2)*.035)+pointerX*.32}function cameraPitch(){return -.08+(reduced?0:Math.sin(progress*Math.PI*2.4)*.025)+pointerY*.2}
function resize(){if(!glActive)return;const dpr=Math.min(devicePixelRatio||1,innerWidth<700?1.35:1.55);const w=Math.max(1,Math.round(innerWidth*dpr)),h=Math.max(1,Math.round(innerHeight*dpr));if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h}draw(performance.now()/1000)}
let frame=0,lastDraw=0,visible=!document.hidden;function draw(t){if(!glActive)return;const secs=t;pointerX+=(targetX-pointerX)*.06;pointerY+=(targetY-pointerY)*.06;buildWorld(secs);lastDraw=performance.now()}
function loop(now){frame=0;if(!visible||!glActive)return;if(now-lastDraw>=1000/30)draw(now/1000);frame=requestAnimationFrame(loop)}function start(){if(!visible||!glActive||reduced||frame)return;frame=requestAnimationFrame(loop)}function stop(){if(frame){cancelAnimationFrame(frame);frame=0}}
document.addEventListener('visibilitychange',()=>{visible=!document.hidden;if(visible){readScroll();draw(performance.now()/1000);start()}else stop()});window.addEventListener('resize',resize,{passive:true});resize();if(reduced){draw(0)}else start();

// Gentle DOM reveals; scroll itself remains native and controls only the world camera/pages.
const revealTargets=[...document.querySelectorAll('.chapter-heading,.story-step,.note-copy,.paper-card,.contact-content')];if('IntersectionObserver'in window&&!reduced){const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.12});revealTargets.forEach(el=>{el.classList.add('reveal');observer.observe(el)})}else revealTargets.forEach(el=>el.classList.add('visible'));
const steps=[...document.querySelectorAll('.story-step')];if('IntersectionObserver'in window){const stepObserver=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)steps.forEach(step=>step.classList.toggle('active',step===e.target))}),{rootMargin:'-36% 0px -36% 0px'});steps.forEach(el=>stepObserver.observe(el))}

// Pointer and keyboard both operate the same paper-fold interaction.
const paper=document.getElementById('paper-card');let held=false;function fold(){held=true;paper.classList.add('is-folded');paper.setAttribute('aria-pressed','true')}function unfold(){held=false;paper.classList.remove('is-folded');paper.setAttribute('aria-pressed','false')}paper.addEventListener('pointerdown',e=>{if(e.button===0){e.preventDefault();paper.setPointerCapture(e.pointerId);fold()}});paper.addEventListener('pointerup',unfold);paper.addEventListener('pointercancel',unfold);paper.addEventListener('lostpointercapture',unfold);paper.addEventListener('keydown',e=>{if((e.key===' '||e.key==='Enter')&&!held){e.preventDefault();fold()}});paper.addEventListener('keyup',e=>{if(e.key===' '||e.key==='Enter')unfold()});paper.addEventListener('blur',unfold);
})();
