import * as THREE from '../../vendor/three.module.js';

const W=1024,H=1280,INK='#292a22',MUTED='#777568',PAPER='#e8e1d2',OLIVE='#71795c',BRASS='#b4a47f';
const pages={
  cover:{kind:'cover',kicker:'JEET / VISHU  ·  FIELD NOTES',title:'Ideas,\ncooked with care.',foot:'A MAKER’S BOOK     /     VOL. 01'},
  insideCover:{kind:'story',number:'00',kicker:'THE FIRST PAGE',title:'A note to\nthe curious.',body:'Good work begins with attention: to the person, to the little details, to the moment an idea becomes clear.',foot:'TURN WHEN YOU’RE READY'},
  title:{kind:'title',number:'00',kicker:'INDEPENDENT WEB CREATOR  /  INDIA',title:'Ideas,\ncooked with care.',body:'A portfolio about turning a good question into a place people want to explore.',foot:'SCROLL TO BEGIN'},
  listen:{kind:'story',number:'01',kicker:'THE POINT OF VIEW',title:'Begin with\na better question.',body:'Before the layout, listen for what someone needs to do. A clear answer gives every next choice a reason.',foot:'LISTEN  ·  SHAPE  ·  MAKE'},
  shape:{kind:'story',number:'02',kicker:'THE MAKING',title:'Give the idea\na point of view.',body:'Structure, rhythm, type and color move together, so the experience feels like it belongs to the idea.',foot:'DETAILS IN SERVICE OF THE WHOLE'},
  build:{kind:'story',number:'03',kicker:'THE BUILD',title:'Make it work\nin the real world.',body:'Build the real thing, refine its edges, and give people a clear, comfortable way to explore.',foot:'A THOUGHT BECOMES SOMETHING REAL'},
  radha:{kind:'community',number:'03',kicker:'SELECTED WORK  /  COMMUNITY',title:'New Radha\nSwami',body:'A welcoming digital home for a community and its shared practice.',foot:'OPEN PROJECT  ↗',href:'https://newradhaswami.pages.dev/'},
  gym:{kind:'gym',number:'04',kicker:'SELECTED WORK  /  FITNESS',title:'India Gym',body:'An energetic front door for people ready to train with intention.',foot:'OPEN PROJECT  ↗',href:'https://indiagym.vercel.app/'},
  croxy:{kind:'croxy',number:'05',kicker:'SELECTED WORK  /  DIGITAL',title:'Croxy',body:'A distinct visual world for a digital experience with a little edge.',foot:'OPEN PROJECT  ↗',href:'https://croxy.pages.dev/'},
  process:{kind:'process',number:'06',kicker:'THE WORKING PAGE',title:'Make room\nfor the good bit.',body:'First drafts are allowed to change shape. Keep what works, fold the rest away, and keep moving.',foot:'— JEET'},
  contact:{kind:'contact',number:'07',kicker:'THE LAST PAGE',title:'What should\nwe cook?',body:'Have a project, a question, or just the start of an idea? Let’s make something useful and unmistakably yours.',foot:'+91 96928 12765  ·  WHATSAPP'},
  colophon:{kind:'end',number:'08',kicker:'COLOPHON',title:'Made with\nintent.',body:'JEET / VISHU\nIndependent web creator\nIndia',foot:'THE END  /  OR A BEGINNING'}
};

function roundedRect(ctx,x,y,w,h,r){ctx.beginPath();ctx.roundRect(x,y,w,h,r)}
function wrap(ctx,text,x,y,maxWidth,lineHeight){for(const paragraph of String(text).split('\n')){let line='';for(const word of paragraph.split(' ')){const next=line?`${line} ${word}`:word;if(ctx.measureText(next).width>maxWidth&&line){ctx.fillText(line,x,y);y+=lineHeight;line=word}else line=next}ctx.fillText(line,x,y);y+=lineHeight}return y}
function grain(ctx,seed){let s=seed>>>0;const rnd=()=>{s=(s*1664525+1013904223)>>>0;return s/4294967296};ctx.save();for(let i=0;i<1500;i++){const x=rnd()*W,y=rnd()*H,a=rnd()*.045;ctx.fillStyle=`rgba(${rnd()>.5?'255,255,255':'53,47,35'},${a})`;ctx.fillRect(x,y,1+rnd()*2,1+rnd()*2)}ctx.restore()}
function rule(ctx,y,x=88,w=W-176,color='#c8bfad'){ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x+w,y);ctx.strokeStyle=color;ctx.lineWidth=1;ctx.stroke()}
function frame(ctx,color='#beb08c'){ctx.strokeStyle=color;ctx.lineWidth=1;ctx.strokeRect(54,54,W-108,H-108);ctx.strokeRect(63,63,W-126,H-126)}
function drawTemple(ctx){const cx=365,top=310,bottom=775;ctx.save();ctx.strokeStyle='#977a53';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(cx-210,bottom);ctx.lineTo(cx-210,top+100);ctx.quadraticCurveTo(cx,top-60,cx+210,top+100);ctx.lineTo(cx+210,bottom);ctx.stroke();ctx.lineWidth=2;ctx.strokeRect(cx-160,top+130,320,335);ctx.beginPath();ctx.moveTo(cx-90,bottom);ctx.lineTo(cx-90,top+225);ctx.quadraticCurveTo(cx,top+110,cx+90,top+225);ctx.lineTo(cx+90,bottom);ctx.stroke();for(const x of [cx-126,cx,cx+126]){ctx.beginPath();ctx.moveTo(x,top+235);ctx.lineTo(x,bottom);ctx.stroke()}ctx.beginPath();ctx.moveTo(cx-245,top+108);ctx.lineTo(cx,top-28);ctx.lineTo(cx+245,top+108);ctx.stroke();ctx.restore()}
function drawGym(ctx){ctx.save();const cx=730,cy=450;const g=ctx.createRadialGradient(cx-35,cy-45,8,cx,cy,230);g.addColorStop(0,'#d1d7b5');g.addColorStop(.48,'#929a72');g.addColorStop(1,'#566049');ctx.fillStyle=g;ctx.beginPath();ctx.arc(cx,cy,190,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#768064';ctx.lineWidth=4;ctx.beginPath();ctx.arc(cx,cy,225,0,Math.PI*2);ctx.stroke();ctx.strokeStyle='#3f4736';ctx.lineWidth=15;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(245,710);ctx.lineTo(920,710);ctx.stroke();ctx.fillStyle='#687458';for(const x of [325,390,775,840]){roundedRect(ctx,x-26,610,52,200,8);ctx.fill()}ctx.restore()}
function drawCroxy(ctx){ctx.save();const cx=696,cy=456;ctx.strokeStyle='#9688a0';ctx.lineWidth=2;for(let i=0;i<3;i++){ctx.beginPath();ctx.ellipse(cx,cy,250-i*55,188-i*47,(i-1)*.46,0,Math.PI*2);ctx.stroke()}ctx.translate(cx,cy);ctx.rotate(-.45);ctx.beginPath();ctx.moveTo(0,-175);ctx.lineTo(148,-62);ctx.lineTo(96,175);ctx.lineTo(-95,114);ctx.closePath();const gr=ctx.createLinearGradient(-120,-160,120,175);gr.addColorStop(0,'#f4efe3');gr.addColorStop(.42,'#b7a6c5');gr.addColorStop(1,'#5b4c67');ctx.fillStyle=gr;ctx.fill();ctx.strokeStyle='#f9f2e4';ctx.lineWidth=2;ctx.stroke();ctx.restore()}
function drawFold(ctx){ctx.save();ctx.fillStyle='#d5cdbd';ctx.beginPath();ctx.moveTo(145,290);ctx.lineTo(760,245);ctx.lineTo(868,910);ctx.lineTo(202,975);ctx.closePath();ctx.fill();ctx.strokeStyle='#a29b8a';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(145,290);ctx.lineTo(516,598);ctx.lineTo(868,910);ctx.moveTo(760,245);ctx.lineTo(516,598);ctx.lineTo(202,975);ctx.stroke();ctx.fillStyle='#eee8da';ctx.beginPath();ctx.moveTo(760,245);ctx.lineTo(868,910);ctx.lineTo(516,598);ctx.closePath();ctx.fill();ctx.restore()}

function illustration(ctx,kind){if(kind==='community')drawTemple(ctx);if(kind==='gym')drawGym(ctx);if(kind==='croxy')drawCroxy(ctx);if(kind==='process')drawFold(ctx);if(kind==='title'){ctx.save();ctx.strokeStyle='#bbb095';ctx.lineWidth=1;for(let i=0;i<4;i++){ctx.beginPath();ctx.ellipse(512,550,210-i*34,210-i*34,0,0,Math.PI*2);ctx.stroke()}ctx.restore()}}
function downscale(source){const result=document.createElement('canvas');result.width=768;result.height=960;result.getContext('2d').drawImage(source,0,0,result.width,result.height);return result}
function createCanvas(spec,back=false){const canvas=document.createElement('canvas');canvas.width=W;canvas.height=H;const ctx=canvas.getContext('2d');if(spec.kind==='cover'){ctx.fillStyle='#202a23';ctx.fillRect(0,0,W,H);grain(ctx,28);frame(ctx,'#b5a47d');ctx.textAlign='center';ctx.fillStyle='#c5b48a';ctx.font='20px "DM Mono",monospace';ctx.fillText('J  /  V',W/2,245);ctx.fillStyle='#eee8da';ctx.font='italic 76px Georgia,serif';wrap(ctx,spec.title,W/2,510,810,88);ctx.fillStyle='#b8ae98';ctx.font='13px "DM Mono",monospace';ctx.fillText(spec.kicker,W/2,H-220);rule(ctx,H-178,180,W-360,'#736c58');ctx.fillText(spec.foot,W/2,H-130);return downscale(canvas)}
  ctx.fillStyle=PAPER;ctx.fillRect(0,0,W,H);grain(ctx,(spec.number||'0').charCodeAt(0)*161+spec.title.length);ctx.textAlign='left';ctx.fillStyle=MUTED;ctx.font='15px "DM Mono",monospace';ctx.fillText(spec.kicker,94,105);ctx.fillStyle=INK;ctx.font='14px "DM Mono",monospace';ctx.fillText(back?'JEET / VISHU  ·  FIELD NOTES':'J / V',94,70);rule(ctx,132);
  if(['community','gym','croxy','process','title'].includes(spec.kind))illustration(ctx,spec.kind);
  if(spec.kind==='title'){ctx.fillStyle=INK;ctx.font='italic 66px Georgia,serif';wrap(ctx,spec.title,92,840,830,78);ctx.fillStyle=MUTED;ctx.font='21px Arial,sans-serif';wrap(ctx,spec.body,96,1046,700,34)}
  else if(spec.kind==='community'||spec.kind==='gym'||spec.kind==='croxy'){ctx.fillStyle=MUTED;ctx.font='14px "DM Mono",monospace';ctx.fillText(`PROJECT  /  ${spec.number}`,95,870);ctx.fillStyle=INK;ctx.font='italic 67px Georgia,serif';wrap(ctx,spec.title,92,958,820,74);ctx.fillStyle=MUTED;ctx.font='20px Arial,sans-serif';wrap(ctx,spec.body,96,1110,800,31);ctx.fillStyle=OLIVE;ctx.font='13px "DM Mono",monospace';ctx.fillText(spec.foot,96,1200)}
  else{ctx.fillStyle=INK;ctx.font='italic 67px Georgia,serif';wrap(ctx,spec.title,92,410,840,80);ctx.fillStyle=MUTED;ctx.font='21px Arial,sans-serif';wrap(ctx,spec.body,96,690,750,35);if(spec.kind==='contact'){ctx.fillStyle='#5d684c';ctx.font='24px "DM Mono",monospace';ctx.fillText('+91 96928 12765',96,1000);ctx.font='14px "DM Mono",monospace';ctx.fillText('WHATSAPP  /  9692812765',96,1050)}ctx.fillStyle=OLIVE;ctx.font='13px "DM Mono",monospace';ctx.fillText(spec.foot,96,1190)}
  rule(ctx,H-90);ctx.fillStyle=MUTED;ctx.font='12px "DM Mono",monospace';ctx.fillText(back?'TURN THE PAGE  ←':'JEET / VISHU  ·  MAKER’S BOOK',96,H-55);ctx.textAlign='right';ctx.fillText(spec.number||'00',W-96,H-55);
  if(back){const mirrored=document.createElement('canvas');mirrored.width=W;mirrored.height=H;const m=mirrored.getContext('2d');m.translate(W,0);m.scale(-1,1);m.drawImage(canvas,0,0);return downscale(mirrored)}return downscale(canvas)}

export function makePageTexture(spec,back=false,renderer){const tex=new THREE.CanvasTexture(createCanvas(spec,back));tex.colorSpace=THREE.SRGBColorSpace;tex.anisotropy=Math.min(6,renderer.capabilities.getMaxAnisotropy());tex.generateMipmaps=true;tex.minFilter=THREE.LinearMipmapLinearFilter;tex.magFilter=THREE.LinearFilter;return tex}
export function createBookPages(renderer){const ids=new Set(['listen','build','gym','process','colophon','insideCover']);return Object.fromEntries(Object.entries(pages).map(([id,spec])=>[id,{front:makePageTexture(spec,false,renderer),back:ids.has(id)?makePageTexture(spec,true,renderer):null,spec}]))}
export function createPaperGrain(){const canvas=document.createElement('canvas');canvas.width=128;canvas.height=128;const ctx=canvas.getContext('2d'),image=ctx.createImageData(128,128);let seed=91273;for(let i=0;i<image.data.length;i+=4){seed=(seed*1664525+1013904223)>>>0;const n=130+(seed%90);image.data[i]=n;image.data[i+1]=n;image.data[i+2]=n;image.data[i+3]=255}ctx.putImageData(image,0,0);const tex=new THREE.CanvasTexture(canvas);tex.wrapS=tex.wrapT=THREE.RepeatWrapping;tex.repeat.set(3.5,4.5);tex.colorSpace=THREE.NoColorSpace;return tex}
export function pageData(){return pages}
